### ISSUE TITLE
Importing a list of URLs as bookmarks

### ISSUE THREAD

**Issue by Immortalin** [lmmx/devnotes#2]
This builds upon your method of importing tabs and allows the tabs to be imported as bookmarks.
Not the cleanest code but works.

This can only be done manually and imported through chrome's import bookmarks in HTML API due to rate limiting.

https://stackoverflow.com/questions/19374378/how-to-import-bookmarks-programmatically

```Javascript
tabs = document.querySelector("#-blink-dev-tools > div.widget.vbox.root-view > div > div > div > div:nth-child(1) > div > div").shadowRoot.querySelector("div > div.hbox.devices-container > div.flex-auto.vbox > div > div.device-browser-list.vbox > div > div.device-page-list.vbox.device-view-more-toggled").querySelectorAll("div.vbox")



str = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
    <DT><H3 ADD_DATE="1536609418" LAST_MODIFIED="1536609442" PERSONAL_TOOLBAR_FOLDER="true">Bookmarks bar</H3>
    <DL><p>`;
for (i=0;i<tabs.length;i++){
  if (tabs[i] != null){
    str += ' <DT><A HREF="' + tabs[i].querySelector('div.device-page-url > x-link').attributes.href.value +' "ADD_DATE="1536609434">'+ tabs[i].querySelector('.device-page-title').textContent + '</A>' +'\n'
  } else {
    console.log(tabs[i])
  }
}

str+=    `</DL><p>
</DL><p>`;
copy(str)
```

Some URLS may have the `chrome-distiller` prefix. These have to be resolved manually as they are web pages that were in `Reader's mode` when imported as tabs. Please feel free to clean up the code, add this to the wiki or spin into a browser extension etc.

**Comment by Immortalin** [comment]
Script updated to fix [Chrome Shadow DOM shenanigans](https://github.com/GoogleChrome/puppeteer/issues/858).  Fixes #3

**Comment by Immortalin** [comment]
Script updated again for latest Chrome version. @lmmx, #3.

**Comment by Hibrix-net** [comment]
Latest Chrome version truncates the URLs taken from here:
`document.querySelectorAll('.subrow-box .url')`
I think we should wait to a Chrome upgrade, because I couldn't find any other source to get those URLs.

What do you think?
