### ISSUE TITLE
24/3/2019 - Exporting Android Chrome Tabs

### ISSUE THREAD

**Issue by planetastro** [lmmx/devnotes#3]
https://github.com/lmmx/devnotes/wiki/Export-all-Chrome-tabs-on-Android
Can't get the code to work anymore as it seems Google changed the structure. This works:

tabs = document.querySelector('#-blink-dev-tools > div.widget.vbox.root-view > div > div > div > div:nth-child(1) > div > div').shadowRoot.querySelectorAll('div > div.hbox.devices-container > div.flex-auto.vbox > div > div.device-browser-list.vbox > div > div.device-page-list.vbox.device-view-more-toggled > .vbox')
str = '';
for (i=0;i<tabs.length;i++){
  if (tabs[i].querySelector('.device-page-url .devtools-link') != null){
    str += '- ['+tabs[i].querySelector('.device-page-title').textContent + '](' + tabs[i].querySelector('.device-page-url .devtools-link').getAttribute('href') +')\n'
  } else {
    console.log(tabs[i])
  }
}
copy(str)

Just the top part. Your code is brilliant, thanks lots for it!

**Comment by miracle2k** [comment]
I think this is because Chrome no longer supports `/deep`/

**Comment by Immortalin** [comment]
@planetastro this can be closed now. See new updated script.

**Comment by lmmx** [comment]
Cool, thanks for the update everyone! @Immortalin I'll add a link to your updated script (I actually switched to Firefox on Android since writing it for Chrome so am not using it myself), glad it's useful for you :+1:
