### ISSUE TITLE
Blank screen, virtual machine not starting up.

### ISSUE THREAD

**Issue by jyothischandran** [lmmx/devnotes#6]
I am having trouble running the original script that you referred from (tried catalina) and your modified script (tried mojave). I have tried with all the cpuids in the original script. I dont think that wil help. I am attaching the troubleshooting file herewith.

[macOS_troubleshoot.txt](https://github.com/lmmx/devnotes/files/6898876/macOS_troubleshoot.txt)

**Comment by lmmx** [comment]
Open an issue on the project in question, this is my personal wiki
